# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/tolymer.proto for package 'tolymer'

require 'grpc'
require 'proto/tolymer_pb'

module Tolymer
  module Hello
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'tolymer.Hello'

      rpc :Greet, GreetRequest, GreetResponse
    end

    Stub = Service.rpc_stub_class
  end
end
