# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/tolymer.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "tolymer.GreetRequest" do
    optional :id, :uint64, 1
  end
  add_message "tolymer.GreetResponse" do
    optional :id, :uint64, 1
    optional :name, :string, 2
  end
end

module Tolymer
  GreetRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.GreetRequest").msgclass
  GreetResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.GreetResponse").msgclass
end
