# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/tolymer.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/field_mask_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "tolymer.v1.Date" do
    optional :year, :int32, 1
    optional :month, :int32, 2
    optional :day, :int32, 3
  end
  add_message "tolymer.v1.GetEventRequest" do
    optional :event_token, :string, 1
  end
  add_message "tolymer.v1.CreateEventRequest" do
    optional :title, :string, 1
    optional :description, :string, 2
    optional :date, :message, 3, "tolymer.v1.Date"
    repeated :participants, :string, 4
  end
  add_message "tolymer.v1.UpdateEventRequest" do
    optional :event_token, :string, 1
    optional :title, :string, 2
    optional :description, :string, 3
    optional :date, :message, 4, "tolymer.v1.Date"
    optional :update_mask, :message, 5, "google.protobuf.FieldMask"
  end
  add_message "tolymer.v1.CreateParticipantRequest" do
    optional :event_token, :string, 1
    optional :name, :string, 2
  end
  add_message "tolymer.v1.UpdateParticipantRequest" do
    optional :event_token, :string, 1
    optional :participant_id, :int64, 2
    optional :name, :string, 3
    optional :update_mask, :message, 4, "google.protobuf.FieldMask"
  end
  add_message "tolymer.v1.DeleteParticipantRequest" do
    optional :event_token, :string, 1
    optional :participant_id, :int64, 2
  end
  add_message "tolymer.v1.CreateGameRequest" do
    optional :event_token, :string, 1
    repeated :scores, :message, 2, "tolymer.v1.Score"
  end
  add_message "tolymer.v1.UpdateGameRequest" do
    optional :event_token, :string, 1
    optional :game, :message, 2, "tolymer.v1.Game"
    optional :update_mask, :message, 3, "google.protobuf.FieldMask"
  end
  add_message "tolymer.v1.DeleteGameRequest" do
    optional :event_token, :string, 1
    optional :game_id, :int64, 2
  end
  add_message "tolymer.v1.CreateTipRequest" do
    optional :event_token, :string, 1
    repeated :tips, :message, 2, "tolymer.v1.Tip"
  end
  add_message "tolymer.v1.UpdateTipRequest" do
    optional :event_token, :string, 1
    repeated :tips, :message, 2, "tolymer.v1.Tip"
    optional :update_mask, :message, 3, "google.protobuf.FieldMask"
  end
  add_message "tolymer.v1.DeleteTipRequest" do
    optional :event_token, :string, 1
  end
  add_message "tolymer.v1.Event" do
    optional :token, :string, 1
    optional :title, :string, 2
    optional :description, :string, 3
    optional :date, :message, 4, "tolymer.v1.Date"
    repeated :participants, :message, 5, "tolymer.v1.Participant"
    repeated :games, :message, 6, "tolymer.v1.Game"
    repeated :tips, :message, 7, "tolymer.v1.Tip"
  end
  add_message "tolymer.v1.Participant" do
    optional :id, :int64, 1
    optional :name, :string, 2
  end
  add_message "tolymer.v1.Game" do
    optional :id, :int64, 1
    optional :event_token, :string, 2
    repeated :scores, :message, 3, "tolymer.v1.Score"
  end
  add_message "tolymer.v1.Score" do
    optional :participant_id, :int64, 1
    optional :point, :float, 2
  end
  add_message "tolymer.v1.Tip" do
    optional :participant_id, :int64, 1
    optional :point, :float, 2
  end
end

module Tolymer
  module V1
    Date = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.v1.Date").msgclass
    GetEventRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.v1.GetEventRequest").msgclass
    CreateEventRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.v1.CreateEventRequest").msgclass
    UpdateEventRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.v1.UpdateEventRequest").msgclass
    CreateParticipantRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.v1.CreateParticipantRequest").msgclass
    UpdateParticipantRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.v1.UpdateParticipantRequest").msgclass
    DeleteParticipantRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.v1.DeleteParticipantRequest").msgclass
    CreateGameRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.v1.CreateGameRequest").msgclass
    UpdateGameRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.v1.UpdateGameRequest").msgclass
    DeleteGameRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.v1.DeleteGameRequest").msgclass
    CreateTipRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.v1.CreateTipRequest").msgclass
    UpdateTipRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.v1.UpdateTipRequest").msgclass
    DeleteTipRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.v1.DeleteTipRequest").msgclass
    Event = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.v1.Event").msgclass
    Participant = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.v1.Participant").msgclass
    Game = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.v1.Game").msgclass
    Score = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.v1.Score").msgclass
    Tip = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.v1.Tip").msgclass
  end
end
