# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/tolymer.proto for package 'tolymer.v1'

require 'grpc'
require 'proto/tolymer_pb'

module Tolymer
  module V1
    module Events
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'tolymer.v1.Events'

        rpc :GetEvent, GetEventRequest, GetEventResponse
        rpc :CreateEvent, CreateEventRequest, CreateEventResponse
        rpc :UpdateEvent, UpdateEventRequest, UpdateEventResponse
        rpc :CreateGame, CreateGameRequest, CreateGameResponse
        rpc :UpdateGame, UpdateGameRequest, UpdateGameResponse
        rpc :DeleteGame, DeleteGameRequest, DeleteGameResponse
        rpc :CreateTip, CreateTipRequest, CreateTipResponse
        rpc :UpdateTip, UpdateTipRequest, UpdateTipResponse
        rpc :DeleteTip, DeleteTipRequest, DeleteTipResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
