# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/tolymer.proto for package 'tolymer.v1'

require 'grpc'
require 'proto/tolymer_pb'

module Tolymer
  module V1
    module Events
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'tolymer.v1.Events'

        rpc :GetEvent, GetEventRequest, Event
        rpc :CreateEvent, CreateEventRequest, Event
        rpc :UpdateEvent, UpdateEventRequest, Event
        rpc :CreateGame, CreateGameRequest, Game
        rpc :UpdateGame, UpdateGameRequest, Game
        rpc :DeleteGame, DeleteGameRequest, Google::Protobuf::Empty
        rpc :CreateTip, CreateTipRequest, Tip
        rpc :UpdateTip, UpdateTipRequest, Tip
        rpc :DeleteTip, DeleteTipRequest, Google::Protobuf::Empty
      end

      Stub = Service.rpc_stub_class
    end
  end
end
